// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://webpiillbgbwgjzkbece.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYnBpaWxsYmdid2dqemtiZWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NTI5NjQsImV4cCI6MjA5NjEyODk2NH0.yUz9IRPjWa1iTgRiMH1RP0E01h_fhvLA2xlP55_gYTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});